apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
stringData: # Use stringData for convenience (Kubernetes base64 encodes it)
  DB_USERNAME: "db-user1"
  DB_PASSWORD: "mySecret!333"
type: Opaque
